# Generated by Django 5.1.7 on 2025-03-18 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('news_category', models.CharField(max_length=100)),
                ('web_url', models.URLField(max_length=600, unique=True)),
                ('img_url', models.URLField(blank=True, max_length=600)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Original article publication date')),
                ('content', models.TextField(blank=True)),
                ('section_id', models.CharField(blank=True, max_length=200)),
                ('section_name', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(default='article', max_length=200)),
                ('prediction', models.BooleanField(default=True, help_text='True = Real News, False = Fake News')),
                ('verification_method', models.CharField(choices=[('gemini', 'Gemini AI'), ('basic', 'Basic Model'), ('error', 'Error')], default='basic', max_length=20)),
                ('verification_details', models.JSONField(blank=True, help_text='Stores detailed verification analysis', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Live News Article',
                'verbose_name_plural': 'Live News Articles',
                'ordering': ['-publication_date'],
                'indexes': [models.Index(fields=['publication_date'], name='core_livene_publica_0e7f7a_idx'), models.Index(fields=['news_category'], name='core_livene_news_ca_888d03_idx'), models.Index(fields=['verification_method'], name='core_livene_verific_f844de_idx')],
            },
        ),
    ]
