# Generated by Django 5.1.7 on 2025-03-18 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_livenews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livenews',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 19, 0, 58, 991356, tzinfo=datetime.timezone.utc), help_text='Article will be automatically removed after this time'),
        ),
    ]
